import Head from 'next/head'
import Header from '../component/CustomHeader'
import 'tailwindcss/tailwind.css'
import Nav from '../component/Nav'
import Results from '../component/Results'
 
export default function Home() {
  return (
    <div>
   
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by Hulu 2.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Header/>
       <Nav/>
       <Results/>
      
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;
  
}
