import Head from 'next/head'
import Header from '../component/CustomHeader'
import 'tailwindcss/tailwind.css'
import Nav from '../component/Nav'
import Results from '../component/Results'
 
import requests from '../utils/requests'
 
export default function Home({results}) {
  console.log('show res', results);
  return (
    <div className='bg-blue-450 py-5  text-gray-300'>
   
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by Hulu 2.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Header/>
       <Nav/>
       <Results results={results}/>
      
    </div>
  )
}

export async function getServerSideProps(context){
  
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url 
  || requests.fetchTrending.url}`).then((res)=>res.json());
 
  return {
    props:{
      results: request.results,
    }
  }
}

const getData = async (genre) => {
  const apiResponse = await fetch(`http://localhost:3000/api/${genre}`).then((res) =>
    res.json()
  );
  // console.log("api res", apiResponse);
  return apiResponse;
};